### PR TITLE
Added button to enable/disable background

### PR DESCRIPTION
**Pull request by nicola02nb**
Added button to enable/disable background

### CODE REVIEW

**Comment by JulienMaille** [comment]
Can you describe the purpose and show the results with some snapshots?
FYI there is already a variant that disable background rotation
image

**Comment by nicola02nb** [comment]
My edit adds a button that completely removes the background making it completely blank for who don't like the backgorund image...
If you don't want it, feel free to reject the idea...

**Comment by nicola02nb** [comment]
I actually didn't know of the NoAnimatio variant, so I'll close the PR

**Comment by JulienMaille** [comment]
Maybe this option should be better advertised but I'm not sure how

**Pull request closed without merging**
