### PR TITLE
Update default-dynamic.js for Spicetify v2.28.1 and reformat code.

### PR DESCRIPTION
**Pull request by obvRedwolf**
This replaces the ```Spicetify.Player.data.track``` property which was removed in Spicetify v2.28.1 with ```Spicetify.Player.data.item```. This allows the album art background to work again.

From Spicetify v2.28.1 changelog:

- ```Spicetify.Player.data.track``` property has been fully removed and has been replaced by ```Spicetify.Player.data.item```.

Code was also reformatted using the Prettier VS Code extension.

### CODE REVIEW

**Comment by JulienMaille** [comment]
Thanks for the PR, however there are a couple issues:
 - replacing data.track with data.item was already done several weeks ago in https://github.com/JulienMaille/spicetify-dynamic-theme/pull/53
 - your PR reverts some changes from that same PR
 - your PR reverts small changes from https://github.com/JulienMaille/spicetify-dynamic-theme/commit/960cf51754c329793024524cb9affdb1b6964557

**Comment by obvRedwolf** [comment]
welp, i guess my local theme was outdated

**Comment by obvRedwolf** [comment]
for some reason, the install script doesn't include those changes

**Comment by JulienMaille** [comment]
The install script ships the latest release, while Spicetify marketplace includes the latest commit.

**Comment by obvRedwolf** [comment]
yeah alright, anyways since we are already talking, is there a way to make the transition from dark mode to light mode and the other way around smoother? it looks like 30 fps and i have hardware acceleration on. maybe up to monitor refresh rate?

**Comment by JulienMaille** [comment]
30fps isn't smooth enough for you? :)
It doesn't feel bad on my setup.
Maybe you could try to add steps here
https://github.com/JulienMaille/spicetify-dynamic-theme/blob/b817aad1347f312c418f811d73395269a8fac352/user.css#L463-L471
Try `--spice-sidebar 0.5s steps(30)`

**Comment by obvRedwolf** [comment]
> --spice-sidebar 0.5s steps(30)

im one of those people who prioritize fps in games instead of looks. anyways, ill try it!

**Comment by obvRedwolf** [comment]
> 30fps isn't smooth enough for you? :) It doesn't feel bad on my setup. Maybe you could try to add steps here
> 
> https://github.com/JulienMaille/spicetify-dynamic-theme/blob/b817aad1347f312c418f811d73395269a8fac352/user.css#L463-L471
> 
> Try `--spice-sidebar 0.5s steps(30)`

is the amount of steps the amount of fps it renders at?

**Comment by obvRedwolf** [comment]
> 30fps isn't smooth enough for you? :) It doesn't feel bad on my setup. Maybe you could try to add steps here
> 
> https://github.com/JulienMaille/spicetify-dynamic-theme/blob/b817aad1347f312c418f811d73395269a8fac352/user.css#L463-L471
> 
> Try `--spice-sidebar 0.5s steps(30)`

thanks! i changed the steps to my monitor refresh rate which is 165 and now its silky smooth! you should make that an option somewhere in the theme, would be a good idea.

**Comment by JulienMaille** [comment]
Since the transition lasts only half a sec you should try to divide this value by 2

**Comment by obvRedwolf** [comment]
> Since the transition lasts only half a sec you should try to divide this value by 2

the transition is really laggy on the home screen even with no steps

**Pull request closed without merging**
