### PR TITLE
Better readme

### PR DESCRIPTION
**Pull request by dyrok**
I spent 45 minutes figuring out how to patch this. This tutorial will greatly reduce the time to patch for people without experience.

### CODE REVIEW

**Comment by JulienMaille** [comment]
Thanks

**Comment by vilev0** [comment]
I think `spicetify -c` prints the correct path

**Comment by JulienMaille** [comment]
> I think `spicetify -c` prints the correct path

what do you mean? Is there anything that can be simplified in the Readme?

**Comment by vilev0** [comment]
Yeah the patching part. I didn't find the file using those instructions, but then I found this command which basically gives you the file path.

Also, doesn't the file get patched automatically with the installer? It was patched already for me. Brw great theme.

**Comment by vilev0** [comment]
You added it, great :)

**Pull request merged**
